// trust-router/ownership_encoding.rs: Ownership VC detection
//
// trust-vc-specific SMT generation deleted — trust_vc_backend removed.
// Only `is_ownership_vc` retained (used by routing.rs).
//
// Author: Andrew Yates <andrewyates.name@gmail.com>
// Copyright 2026 Andrew Yates | License: Apache 2.0

use trust_types::{VcKind, VerificationCondition};

/// Trust: #178 Detect whether a VC is an ownership-related VC.
///
/// Returns `true` for VCs generated by trust_vcgen/region_encoding.rs which
/// use VcKind::Assertion with a `[memory:region]` prefix.
#[must_use]
pub(crate) fn is_ownership_vc(vc: &VerificationCondition) -> bool {
    match &vc.kind {
        VcKind::Assertion { message } => message.starts_with("[memory:region]"),
        _ => false,
    }
}

#[cfg(test)]
mod tests {
    use trust_types::*;

    use super::*;

    #[test]
    fn test_is_ownership_vc_with_region_prefix() {
        let vc = VerificationCondition {
            kind: VcKind::Assertion {
                message: "[memory:region] non-aliasing: region_0 vs region_1".to_string(),
            },
            function: "test_fn".into(),
            location: SourceSpan::default(),
            formula: Formula::Bool(true),
            contract_metadata: None,
        };
        assert!(is_ownership_vc(&vc));
    }

    #[test]
    fn test_is_ownership_vc_without_prefix() {
        let vc = VerificationCondition {
            kind: VcKind::DivisionByZero,
            function: "test".into(),
            location: SourceSpan::default(),
            formula: Formula::Bool(true),
            contract_metadata: None,
        };
        assert!(!is_ownership_vc(&vc));
    }

    #[test]
    fn test_is_ownership_vc_non_memory_assertion() {
        let vc = VerificationCondition {
            kind: VcKind::Assertion { message: "some other assertion".to_string() },
            function: "test".into(),
            location: SourceSpan::default(),
            formula: Formula::Bool(true),
            contract_metadata: None,
        };
        assert!(!is_ownership_vc(&vc));
    }
}
