[book]
title = "The trustc book"

[output.html]
git-repository-url = "https://github.com/alabsystems/Trust/tree/main/src/doc/rustc"
edit-url-template = "https://github.com/alabsystems/Trust/edit/main/src/doc/rustc/{path}"

[output.html.search]
use-boolean-and = true

[output.html.playground]
runnable = false
