.TH TRUSTDOC "1" "April 2026" "trustdoc <INSERT VERSION HERE>" "User Commands"
.SH NAME
trustdoc \- Generate documentation with the Trust toolchain
.SH SYNOPSIS
.B trustdoc
[\fIOPTIONS\fR] \fIINPUT\fR
.SH DESCRIPTION
\fBtrustdoc\fR is the canonical documentation binary for the Trust toolchain.
.SH SEE ALSO
.BR trustc (1)
