- // MIR for `different_indices` before RedundantBoundsCheckElim
+ // MIR for `different_indices` after RedundantBoundsCheckElim
  
  fn different_indices(_1: &[i32], _2: usize, _3: usize) -> (i32, i32) {
      debug x => _1;
      debug i => _2;
      debug j => _3;
      let mut _0: (i32, i32);
      let mut _4: i32;
      let _5: usize;
      let mut _6: usize;
      let mut _7: bool;
      let mut _8: i32;
      let _9: usize;
      let mut _10: usize;
      let mut _11: bool;
  
      bb0: {
          StorageLive(_4);
          StorageLive(_5);
          _5 = copy _2;
          _6 = PtrMetadata(copy _1);
          _7 = Lt(copy _2, copy _6);
          assert(move _7, "index out of bounds: the length is {} but the index is {}", copy _6, copy _2) -> [success: bb1, unwind continue];
      }
  
      bb1: {
          _4 = copy (*_1)[_2];
          StorageLive(_8);
          StorageLive(_9);
          _9 = copy _3;
          _10 = copy _6;
          _11 = Lt(copy _3, copy _6);
          assert(move _11, "index out of bounds: the length is {} but the index is {}", copy _6, copy _3) -> [success: bb2, unwind continue];
      }
  
      bb2: {
          _8 = copy (*_1)[_3];
          _0 = (move _4, move _8);
          StorageDead(_8);
          StorageDead(_4);
          StorageDead(_9);
          StorageDead(_5);
          return;
      }
  }
  
