- // MIR for `switch_to_eq_unequal` before MatchBranchSimplification
+ // MIR for `switch_to_eq_unequal` after MatchBranchSimplification
  
  fn switch_to_eq_unequal(_1: u32, _2: &mut u32) -> u32 {
      let mut _0: u32;
+     let mut _3: bool;
  
      bb0: {
-         switchInt(copy _1) -> [42: bb1, otherwise: bb2];
+         _3 = Eq(copy _1, const 42_u32);
+         switchInt(move _3) -> [0: bb2, otherwise: bb1];
      }
  
      bb1: {
          (*_2) = const 1_u32;
          _0 = const 100_u32;
          goto -> bb3;
      }
  
      bb2: {
          _0 = const 200_u32;
          goto -> bb3;
      }
  
      bb3: {
          return;
      }
  }
  
