use super::validate::{
    expect_exact_transcript_keys, expect_key_values, expect_unix_file_id, single_key_value,
};

pub(super) fn validate_additional_walkthroughs(stdout: &str) -> Vec<String> {
    let mut errors = Vec::new();
    expect_key_values(
        stdout,
        "walkthrough",
        &[
            "permissions",
            "raw_path_re_resolution",
            "error_discard_integrity",
            "panic_boundary",
            "process_sigpipe",
            "cli_args",
            "trust_domain_order",
            "unsafe_ffi_boundary_inventory",
            "ffi_boundary_inventory",
        ],
        &mut errors,
    );
    if cfg!(unix) {
        expect_exact_transcript_keys(
            stdout,
            &[
                "walkthrough",
                "scratch",
                "create_parent_file_id",
                "create_parent_identity_verified",
                "create_new_requested_mode",
                "create_new_group_other_bits",
                "chmod_file_id_before",
                "chmod_file_id_after",
                "chmod_identity_stable",
                "chmod_window_start_mode",
                "chmod_window_final_mode",
                "create_dir_requested_mode",
                "create_dir_creation_mode",
                "chmod_change_observed",
                "rootless_scope",
                "result",
                "walkthrough",
                "scratch",
                "checked_path",
                "initial_target",
                "replacement_target",
                "pre_canonical_leaf",
                "post_canonical_leaf",
                "pre_file_id",
                "post_file_id",
                "pre_read",
                "post_read",
                "raw_path_re_resolved",
                "raw_path_scope",
                "result",
                "walkthrough",
                "scratch",
                "expected_len",
                "discarded_remove_error",
                "discarded_canonicalize_error",
                "checked_read_error",
                "discarded_read_error",
                "discarded_fallback_len",
                "fallback_matches_expected",
                "checked_decision",
                "fallback_decision",
                "integrity_check",
                "result",
                "walkthrough",
                "scratch",
                "safe_metadata",
                "safe_utf8",
                "panic_hook",
                "caught_panics",
                "caught_panic_count",
                "panic_payloads_escaped",
                "result",
                "walkthrough",
                "closed_stream_write_error",
                "sigpipe_child_stdout_closed",
                "sigpipe_child_exit",
                "broken_pipe_handled",
                "result",
                "walkthrough",
                "parent_args_os_count",
                "cli_child_mode",
                "cli_child_arg_count",
                "cli_child_space_arg",
                "cli_child_invalid_arg_hex",
                "cli_child_invalid_arg_to_str",
                "cli_child_strict_utf8",
                "result",
                "walkthrough",
                "scratch",
                "rootless_root_metadata",
                "rootless_root_canonicalize",
                "rootless_user_probe",
                "rootless_group_probe",
                "rootless_plugin_metadata",
                "rootless_plugin_canonicalize",
                "rootless_plugin_read",
                "pre_privilege_probe_order",
                "privileged_ops",
                "privileged_ops_executed",
                "privileged_ops_mode",
                "root_transition_effect",
                "uid_gid_transition_effect",
                "nss_inside_chroot",
                "dynamic_loader_inside_chroot",
                "evidence_scope",
                "safe_trace",
                "unsafe_trace",
                "safe_trace_late_lookups",
                "unsafe_trace_late_lookups",
                "result",
                "walkthrough",
                "unsafe_pointer_probe",
                "unsafe_block_count",
                "walkthrough",
                "ffi_declared",
                "ffi_called",
                "ffi_call_count",
                "strlen_result",
                "getenv_path",
                "inventory_count",
                "result",
            ],
            &mut errors,
        );
        for (key, value) in [
            ("create_parent_identity_verified", "yes"),
            ("create_new_requested_mode", "0o600"),
            ("create_new_group_other_bits", "0o000"),
            ("chmod_identity_stable", "yes"),
            ("chmod_window_start_mode", "0o644"),
            ("chmod_window_final_mode", "0o600"),
            ("create_dir_requested_mode", "0o700"),
            ("create_dir_creation_mode", "0o700"),
            ("checked_path", "raw-candidate"),
            ("initial_target", "raw-trusted.txt"),
            ("replacement_target", "raw-replacement.txt"),
            ("pre_canonical_leaf", "raw-trusted.txt"),
            ("post_canonical_leaf", "raw-replacement.txt"),
            ("pre_read", "trusted"),
            ("post_read", "replacement"),
            ("raw_path_re_resolved", "yes"),
            ("raw_path_scope", "metadata,canonicalize,symlink,rename,read"),
            ("closed_stream_write_error", "BrokenPipe"),
            ("sigpipe_child_stdout_closed", "yes"),
            ("sigpipe_child_exit", "success"),
            ("broken_pipe_handled", "ok"),
            ("cli_child_mode", "args_os"),
            ("cli_child_space_arg", "preserved"),
            ("cli_child_invalid_arg_hex", "6172675fff"),
            ("cli_child_invalid_arg_to_str", "none"),
            ("cli_child_strict_utf8", "error"),
            ("rootless_user_probe", "ok"),
            ("rootless_group_probe", "ok"),
            ("privileged_ops_executed", "no"),
            ("privileged_ops_mode", "simulated"),
            ("root_transition_effect", "not_exercised"),
            ("uid_gid_transition_effect", "not_exercised"),
            ("nss_inside_chroot", "not_exercised"),
            ("dynamic_loader_inside_chroot", "not_exercised"),
            ("evidence_scope", "rootless_preflight_and_trace_order"),
            ("ffi_declared", "getenv,strlen"),
            ("ffi_called", "getenv,strlen"),
            ("ffi_call_count", "2"),
            ("strlen_result", "5"),
            ("unsafe_pointer_probe", "ok"),
            ("unsafe_block_count", "1"),
            ("inventory_count", "3"),
        ] {
            expect_key_values(stdout, key, &[value], &mut errors);
        }
        let pre_id = single_key_value(stdout, "pre_file_id", &mut errors);
        let post_id = single_key_value(stdout, "post_file_id", &mut errors);
        let create_parent_id = single_key_value(stdout, "create_parent_file_id", &mut errors);
        let chmod_before_id = single_key_value(stdout, "chmod_file_id_before", &mut errors);
        let chmod_after_id = single_key_value(stdout, "chmod_file_id_after", &mut errors);
        if let Some(pre_id) = pre_id {
            expect_unix_file_id(pre_id, &mut errors);
        }
        if let Some(post_id) = post_id {
            expect_unix_file_id(post_id, &mut errors);
        }
        if let Some(create_parent_id) = create_parent_id {
            expect_unix_file_id(create_parent_id, &mut errors);
        }
        if let Some(chmod_before_id) = chmod_before_id {
            expect_unix_file_id(chmod_before_id, &mut errors);
        }
        if let Some(chmod_after_id) = chmod_after_id {
            expect_unix_file_id(chmod_after_id, &mut errors);
        }
        if pre_id.zip(post_id).is_some_and(|(pre, post)| pre == post) {
            errors.push("raw path walkthrough kept the same file identity".to_string());
        }
        if chmod_before_id.zip(chmod_after_id).is_some_and(|(before, after)| before != after) {
            errors.push("chmod walkthrough changed file identity".to_string());
        }
        expect_key_values(
            stdout,
            "result",
            &[
                "permission-window-create-change-demonstrated",
                "raw-path-re-resolution-demonstrated",
                "error-discard-integrity-demonstrated",
                "panic-boundary-demonstrated",
                "process-sigpipe-demonstrated",
                "cli-arg-compatibility-demonstrated",
                "trust-domain-order-demonstrated-rootlessly",
                "unsafe-ffi-boundary-inventory-demonstrated",
            ],
            &mut errors,
        );
    } else {
        expect_exact_transcript_keys(
            stdout,
            &[
                "walkthrough",
                "permissions_unsupported",
                "walkthrough",
                "raw_path_unsupported",
                "walkthrough",
                "scratch",
                "expected_len",
                "discarded_remove_error",
                "discarded_canonicalize_error",
                "checked_read_error",
                "discarded_read_error",
                "discarded_fallback_len",
                "fallback_matches_expected",
                "checked_decision",
                "fallback_decision",
                "integrity_check",
                "result",
                "walkthrough",
                "scratch",
                "safe_metadata",
                "safe_utf8",
                "panic_hook",
                "caught_panics",
                "caught_panic_count",
                "panic_payloads_escaped",
                "result",
                "walkthrough",
                "sigpipe_unsupported",
                "walkthrough",
                "cli_args_unsupported",
                "walkthrough",
                "scratch",
                "rootless_root_metadata",
                "rootless_root_canonicalize",
                "rootless_user_probe",
                "rootless_group_probe",
                "rootless_plugin_metadata",
                "rootless_plugin_canonicalize",
                "rootless_plugin_read",
                "pre_privilege_probe_order",
                "privileged_ops",
                "privileged_ops_executed",
                "privileged_ops_mode",
                "root_transition_effect",
                "uid_gid_transition_effect",
                "nss_inside_chroot",
                "dynamic_loader_inside_chroot",
                "evidence_scope",
                "safe_trace",
                "unsafe_trace",
                "safe_trace_late_lookups",
                "unsafe_trace_late_lookups",
                "result",
                "walkthrough",
                "walkthrough",
                "ffi_unsupported",
            ],
            &mut errors,
        );
        for (key, value) in [
            ("permissions_unsupported", "non-unix"),
            ("raw_path_unsupported", "non-unix"),
            ("sigpipe_unsupported", "non-unix"),
            ("cli_args_unsupported", "non-unix"),
            ("rootless_user_probe", "unsupported"),
            ("rootless_group_probe", "unsupported"),
            ("privileged_ops_executed", "no"),
            ("privileged_ops_mode", "simulated"),
            ("root_transition_effect", "not_exercised"),
            ("uid_gid_transition_effect", "not_exercised"),
            ("nss_inside_chroot", "not_exercised"),
            ("dynamic_loader_inside_chroot", "not_exercised"),
            ("evidence_scope", "rootless_preflight_and_trace_order"),
            ("ffi_unsupported", "non-unix"),
        ] {
            expect_key_values(stdout, key, &[value], &mut errors);
        }
        expect_key_values(
            stdout,
            "result",
            &[
                "error-discard-integrity-demonstrated",
                "panic-boundary-demonstrated",
                "trust-domain-order-demonstrated-rootlessly",
            ],
            &mut errors,
        );
    }
    for (key, value) in [
        ("discarded_remove_error", "NotFound"),
        ("discarded_canonicalize_error", "NotFound"),
        ("checked_read_error", "NotFound"),
        ("discarded_read_error", "lost"),
        ("discarded_fallback_len", "0"),
        ("fallback_matches_expected", "no"),
        ("checked_decision", "reject-error"),
        ("fallback_decision", "reject-empty-fallback"),
        ("integrity_check", "discard-changes-decision"),
        ("safe_metadata", "ok"),
        ("safe_utf8", "ok"),
        ("panic_hook", "suppressed"),
        ("caught_panics", "metadata_expect,utf8_unwrap,assert,panic,todo,unreachable"),
        ("caught_panic_count", "6"),
        ("panic_payloads_escaped", "no"),
        ("rootless_root_metadata", "ok"),
        ("rootless_root_canonicalize", "ok"),
        ("rootless_plugin_metadata", "ok"),
        ("rootless_plugin_canonicalize", "ok"),
        ("rootless_plugin_read", "ok"),
        ("pre_privilege_probe_order", "root,user,group,plugin"),
        ("privileged_ops", "simulate_chroot,simulate_setgid,simulate_setuid"),
        ("privileged_ops_executed", "no"),
        ("privileged_ops_mode", "simulated"),
        ("root_transition_effect", "not_exercised"),
        ("uid_gid_transition_effect", "not_exercised"),
        ("nss_inside_chroot", "not_exercised"),
        ("dynamic_loader_inside_chroot", "not_exercised"),
        ("evidence_scope", "rootless_preflight_and_trace_order"),
        (
            "safe_trace",
            "resolve_root,resolve_user,getpwnam,resolve_group,getgrnam,resolve_plugin_path,dlopen,simulate_chroot,simulate_setgid,simulate_setuid",
        ),
        (
            "unsafe_trace",
            "simulate_chroot,resolve_user,getpwnam,resolve_group,getgrnam,resolve_plugin_path,dlopen,simulate_setgid,simulate_setuid",
        ),
        ("safe_trace_late_lookups", "0"),
        ("unsafe_trace_late_lookups", "6"),
    ] {
        expect_key_values(stdout, key, &[value], &mut errors);
    }
    errors
}
