//@ battery-lane: B-lean
//@ battery-expect: pass
//@ battery-flags: -Ztrust-verify=off --crate-type=lib
//! LANE B (Lean) — BOOLEAN / DECIDABILITY reasoning by a REAL case split.
//!
//! `b1` proves by `rfl` and reflexivity; `b3` composes `Nat.le` library lemmas.
//! Neither makes the kernel do the one thing a decision procedure actually
//! requires: SPLIT ON A BOOL WHOSE VALUE IT DOES NOT KNOW. Every theorem below
//! does, and the first two are provably NOT closable by `rfl` — `Bool.not
//! (Bool.not b)` is stuck on a variable `b`, so the kernel has to instantiate a
//! motive at `Bool.false` and at `Bool.true` and typecheck two DIFFERENT minor
//! premises.
//!
//! The subject is the bridge Trust's own contracts ride on. `Nat.ble` is the
//! `Bool`-valued DECISION PROCEDURE; `Nat.le` is the `Prop`-valued
//! PROPOSITION; `Nat.le_of_ble_eq_true` and `Nat.ble_eq_true_of_le` are its two
//! directions. `c1_cited_min2.rs` discharges a Rust postcondition through
//! exactly this shape, so pinning it in a pure-Lean file separates "the kernel
//! can do decidability" from "the Rust clause lane wired it up".
//!
//! Pinned to `-Ztrust-verify=off` for the same reason as `b1`: island parsing,
//! elaboration and KERNEL CHECKING are mandatory on every build regardless of
//! the verify flag, so a pass here is evidence about the kernel alone.
//!
//! Every constant used below is registered in the Clean kernel environment —
//! verified against `first-party/clean/crates/clean-kernel/src/env/`:
//!
//! | constant | declaration site |
//! |---|---|
//! | `Bool`, `Bool.false`, `Bool.true` | `data_types_nat.rs:58-78` |
//! | `Bool.not` (reducible def, `Bool.rec`-based) | `data_types_nat.rs:113-119` |
//! | `Bool.rec` | generated by `add_inductive` for `Bool`; motive order `motive Bool.false → motive Bool.true → (t : Bool) → motive t` is stated at `data_types_nat.rs:84` |
//! | `Nat.le`, `Nat.le.refl` | `order_le_lt.rs:212-218` |
//! | `Nat.ble` (reducible def) | `order_nat_cmp.rs:543` |
//! | `Nat.le_of_ble_eq_true : ∀ a b, ble a b = true → Nat.le a b` | `algebra_nat_ble_le_proof.rs:537` |
//! | `Nat.ble_eq_true_of_le : ∀ a b, Nat.le a b → ble a b = true` | `algebra_nat_ble_le_proof.rs:288` |
//! | `Eq`, `Eq.refl` | `core_eq/recursors.rs:64-74` |
//! | `UInt64.toNat` | `data_types_uint.rs:114-115` |
//!
//! Both bridge lemmas are asserted axiom-free by the kernel's own test
//! (`algebra_nat_ble_le_proof.rs:554-573` requires `env.axiom_deps` to be
//! empty), so nothing here leans on an axiom.
//!
//! Argument convention follows the shipped fixtures: lemma arguments are
//! EXPLICIT (`Nat.le_of_ble_eq_true (UInt64.toNat x) (UInt64.toNat y) h`), as
//! in `tests/ui/trust/e9_one_program_two_languages.rs:29`. Comments are kept
//! OUT of the island: it is delimited by Rust token trees, so a `}` inside a
//! Lean comment changes the boundary
//! (`tests/ui/trust/clean_island_lexical_line_comment.rs`).
//!
//! Reading the theorems, in order:
//!
//! 1. `bool_double_negation` — the pure case split. Not `rfl`: the two minor
//!    premises have different types (`Eq Bool Bool.false Bool.false` and
//!    `Eq Bool Bool.true Bool.true`) that only appear AFTER the kernel
//!    iota-reduces the motive at each constructor.
//! 2. `ble_decides_le` — the DEPENDENT case split: the motive is a function
//!    type, so each branch receives a differently-typed hypothesis and is
//!    discharged by a DIFFERENT justification (`Nat.le.refl` on the false
//!    branch, the bridge lemma on the true branch). This is the shape a
//!    decision procedure has.
//! 3. `ble_selects_le` — reflection: instantiate (2) at the decision's own
//!    value and let `Eq.refl` supply the hypothesis. This is what turns "if I
//!    knew the bit I could prove it" into an unconditional theorem.
//! 4. `ble_refl_true` — the Prop → Bool direction, derived rather than cited.
//! 5. `le_ble_roundtrip` — Prop → Bool → Prop. The STATEMENT is weak (`h`
//!    alone would prove it); the content is in the PROOF TERM, which forces the
//!    kernel to typecheck the full round trip through both bridge lemmas. It is
//!    listed as what it is, not as a strong theorem.

clean {
    theorem bool_double_negation : forall (b : Bool),
        Eq Bool (Bool.not (Bool.not b)) b :=
        fun b => Bool.rec
            (fun bb => Eq Bool (Bool.not (Bool.not bb)) bb)
            (Eq.refl Bool Bool.false)
            (Eq.refl Bool Bool.true)
            b

    theorem ble_decides_le : forall (x y : UInt64) (d : Bool),
        Eq Bool (Nat.ble (UInt64.toNat x) (UInt64.toNat y)) d ->
        Nat.le (UInt64.toNat (Bool.rec (fun _ => UInt64) y x d)) (UInt64.toNat y) :=
        fun x y d => Bool.rec
            (fun dd => Eq Bool (Nat.ble (UInt64.toNat x) (UInt64.toNat y)) dd ->
                Nat.le (UInt64.toNat (Bool.rec (fun _ => UInt64) y x dd)) (UInt64.toNat y))
            (fun h => Nat.le.refl (UInt64.toNat y))
            (fun h => Nat.le_of_ble_eq_true (UInt64.toNat x) (UInt64.toNat y) h)
            d

    theorem ble_selects_le : forall (x y : UInt64),
        Nat.le (UInt64.toNat (Bool.rec (fun _ => UInt64) y x
            (Nat.ble (UInt64.toNat x) (UInt64.toNat y))))
            (UInt64.toNat y) :=
        fun x y => ble_decides_le x y (Nat.ble (UInt64.toNat x) (UInt64.toNat y))
            (Eq.refl Bool (Nat.ble (UInt64.toNat x) (UInt64.toNat y)))

    theorem ble_refl_true : forall (a : Nat),
        Eq Bool (Nat.ble a a) Bool.true :=
        fun a => Nat.ble_eq_true_of_le a a (Nat.le.refl a)

    theorem le_ble_roundtrip : forall (a b : Nat),
        Nat.le a b -> Nat.le a b :=
        fun a b h => Nat.le_of_ble_eq_true a b (Nat.ble_eq_true_of_le a b h)
}

/// The Rust program the island is reasoning about. Lane B carries no clause:
/// the measurement is that vanilla Rust still compiles beside a genuinely
/// proof-carrying island, and that the kernel checked the island anyway.
/// `c1_cited_min2.rs` is where this selection acquires a contract.
pub fn select_le(x: u64, y: u64) -> u64 {
    if x <= y { x } else { y }
}
